### ISSUE TITLE
BUG invalid memory address or nil pointer dereference in pkg/client/listen/v1/rest/client.go New()

### ISSUE THREAD

**Issue by eslam-mahmoud** [deepgram/deepgram-go-sdk#266]
## What is the current behavior?
if send `nil` to `deepgram-go-sdk/pkg/client/listen"`.`NewREST` in the second argument 
we get `"invalid memory address or nil pointer dereference"`
```
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/deepgram/deepgram-go-sdk/pkg/client/listen/v1/rest.New({0xc000132420, 0x28}, 0x7f82073c95b8?)
/Users/eslam/go/pkg/mod/github.com/deepgram/deepgram-go-sdk@v1.6.1/pkg/client/listen/v1/rest/client.go:51 +0x27
github.com/deepgram/deepgram-go-sdk/pkg/client/listen.NewREST(...)
/Users/eslam/go/pkg/mod/github.com/deepgram/deepgram-go-sdk@v1.6.1/pkg/client/listen/client.go:47
```

## Steps to reproduce
```go
package main

import (
	deepgramAPI "github.com/deepgram/deepgram-go-sdk/pkg/api/listen/v1/rest"
	deepgramClient "github.com/deepgram/deepgram-go-sdk/pkg/client/listen"
)

func main() {
        deepGrampAPIKey := "123"
	dg := deepgramAPI.New(deepgramClient.NewREST(deepGrampAPIKey, nil))
	_ = dg
}
```

## Workaround 
```go
package main

import (
	deepgramAPI "github.com/deepgram/deepgram-go-sdk/pkg/api/listen/v1/rest"
	deepgramClient "github.com/deepgram/deepgram-go-sdk/pkg/client/listen"
	"github.com/deepgram/deepgram-go-sdk/pkg/client/interfaces"
)

func main() {
        deepGrampAPIKey := "123"
	dg := deepgramAPI.New(deepgramClient.NewREST(deepGrampAPIKey, &interfaces.ClientOptions{}))
	_ = dg
}
```

## Suggested fix
In 
https://github.com/deepgram/deepgram-go-sdk/blob/30cd597e17a2ea5d56614b0a9641aa44e5b4685f/pkg/client/listen/v1/rest/client.go#L49C1-L63C2
instead of
```go
func New(apiKey string, options *interfaces.ClientOptions) *Client {
	if apiKey != "" {
		options.APIKey = apiKey
	}
	err := options.Parse()
	if err != nil {
		klog.V(1).Infof("options.Parse() failed. Err: %v\n", err)
		return nil
	}

	c := Client{
		common.NewREST(apiKey, options),
	}
	return &c
}
```
change it to
```go
func New(apiKey string, options *interfaces.ClientOptions) *Client {
	if options == nil {
		options = &interfaces.ClientOptions{}
	}
	if apiKey != "" {
		options.APIKey = apiKey
	}
	err := options.Parse()
	if err != nil {
		klog.V(1).Infof("options.Parse() failed. Err: %v\n", err)
		return nil
	}

	c := Client{
		common.NewREST(apiKey, options),
	}
	return &c
}
```

**Comment by dvonthenen** [comment]
Hi @eslam-mahmoud 

The documentation does call out that it is required, but this is good enhancement. Previously, this wasn't a pointer to the struct. When I get chance, I will add this.
